
package com.jimboy.forelecto;

import java.util.HashMap;
import java.util.Map;

public class FilipinoToBolinaoTranslator {

    private Map<String, String> translationDict;

    public FilipinoToBolinaoTranslator() {
        translationDict = new HashMap<>();
        // Add translations to the map
        translationDict.put("bahagi ng katawan", "lalaman");
        translationDict.put("buto", "but'oi");
        translationDict.put("ulo", "ulo");
        translationDict.put("mukha", "rupa");
        translationDict.put("noo", "waleng");
        translationDict.put("buhok", "sabot");
        translationDict.put("mata", "mata");
        translationDict.put("tainga", "tutuiyan");
        translationDict.put("aba", "madidintëk");
        translationDict.put("abaka", "abaka");
        translationDict.put("abala", "abara'");
        translationDict.put("abalahin", "abaraën");
        translationDict.put("abay", "abay");
        translationDict.put("abiso", "patanda'");
        translationDict.put("abo", "ariw");
        translationDict.put("abokado", "abukado");
        translationDict.put("abot", "gawang");
        translationDict.put("abridor", "abridor");
        translationDict.put("Abril", "Abril");
        translationDict.put("abutan", "tudulan");
        translationDict.put("abútan", "abutën");
        translationDict.put("abutin", "gawangën");
        translationDict.put("abútin", "abutën");
        translationDict.put("agad", "tampor");
        translationDict.put("agapay", "ampad");
        translationDict.put("agarin", "tampurën");
        translationDict.put("agaw", "sampat");
        translationDict.put("agila", "agila");
        translationDict.put("aginaldo", "krismas");
        translationDict.put("agos", "kuryinti");
        translationDict.put("Agosto", "Agosto");
        translationDict.put("agusan", "agusan");
        translationDict.put("ahas", "ulay");
        translationDict.put("ahitin", "kiskisën");
        translationDict.put("ahon", "arwas");
        translationDict.put("akasya", "akasya");
        translationDict.put("akay", "tabin");
        translationDict.put("akayin", "tabinën");
        translationDict.put("akbay", "kuyaba");
        translationDict.put("akbayan", "gayëmën");
        translationDict.put("akit", "ayat");
        translationDict.put("aklat", "libro");
        translationDict.put("ako", "si'ko");
        translationDict.put("akó", "ako");
        translationDict.put("ákò", "ako'");
        translationDict.put("aksaya", "anam");
        translationDict.put("aksaya", "pirdi");
        translationDict.put("aktibo", "aktibo");
        translationDict.put("akuin", "alilbiën");
        translationDict.put("akuin", "akuën");
        translationDict.put("akyat", "uli'");
        translationDict.put("akyatin", "uliën");
        translationDict.put("alab", "ma'mot");
        translationDict.put("alab", "amot");
        translationDict.put("alaga", "alila'");
        translationDict.put("alagaan", "pagawan");
        translationDict.put("alagaan", "alilaën");
        translationDict.put("alahas", "alahas");
        translationDict.put("alak", "arak");
        translationDict.put("alak-alakan", "tikër");
        translationDict.put("alakdan", "sipitan");
        translationDict.put("alam", "tanda'");
        translationDict.put("alamang", "aramang");
        translationDict.put("alambre", "alamri");
        translationDict.put("alambrihan", "alamryën");
        translationDict.put("alamin", "tandaën");
        translationDict.put("alas", "alas");
        translationDict.put("alay", "da'ton");
        translationDict.put("ale", "dada'");
        translationDict.put("alikabok", "ta'pok");
        translationDict.put("alilain", "alilaën");
        translationDict.put("alimango", "ayama");
        translationDict.put("alimasag", "barisaway");
        translationDict.put("alimpuyo", "alisëdsëd");
        translationDict.put("alin", "ayi");
        translationDict.put("alin", "aya");
        translationDict.put("alipato", "lëyëw");
        translationDict.put("alipin", "aripën");
        translationDict.put("alipunga", "alipunga");
        translationDict.put("alis", "lakwan");
        translationDict.put("alis", "ibwat");
        translationDict.put("alisan", "galatan");
        translationDict.put("alisin", "galtën");
        translationDict.put("alisto", "alisto");
        translationDict.put("alitaptap", "kalitëptëp");
        translationDict.put("aliw", "liwaliwa");
        translationDict.put("alkansya", "alkansya");
        translationDict.put("alkohol", "arkuhol");
        translationDict.put("almusal", "armusal");
        translationDict.put("alo", "kuyong");
        translationDict.put("alog", "kalog");
        translationDict.put("alon", "ballayon");
        translationDict.put("alon", "daluyon");
        translationDict.put("alpabeto", "alpabito");
        translationDict.put("alsa", "kubo");
        translationDict.put("altar", "altar");
        translationDict.put("aluin", "kuyungën");
        translationDict.put("alulong", "taol");
        translationDict.put("alun-alon", "rimrim");
        translationDict.put("alupihan", "gayaman");
        translationDict.put("am", "lasaw");
        translationDict.put("ama", "ama");
        translationDict.put("amag", "burtabot");
        translationDict.put("amanos", "amanos");
        translationDict.put("amba", "awad");
        translationDict.put("amba", "patyo'");
        translationDict.put("ambaan", "patyuan");
        translationDict.put("ambaan", "awadan");
        translationDict.put("ambag", "ur'or");
        translationDict.put("ambisyon", "ambisyon");
        translationDict.put("ambon", "darumadim");
        translationDict.put("ambulansiya", "ambulansya");
        translationDict.put("Amerika", "Amerika");
        translationDict.put("amihan", "amyan");
        translationDict.put("amihan", "aramag");
        translationDict.put("amo", "amo");
        translationDict.put("amo", "amo'");
        translationDict.put("amo", "uyamo'");
        translationDict.put("amoy", "angot");
        translationDict.put("amoy bulok", "bangor");
        translationDict.put("ampalaya", "parya'");
        translationDict.put("ampon", "ampon");
        translationDict.put("amuyin", "angutën");
        translationDict.put("anahaw", "anahaw");
        translationDict.put("anahaw", "bulanday");
        translationDict.put("anak", "anak");
        translationDict.put("an-an", "kadis");
        translationDict.put("anay", "anag");
        translationDict.put("anayin", "anagën");
        translationDict.put("andar", "andar");
        translationDict.put("ang", "say");
        translationDict.put("ang", "a");
        translationDict.put("ang mga iyan", "sarain");
        translationDict.put("ang mga iyon", "saraytaw");
        translationDict.put("ang mga iyon", "saytaw");
        translationDict.put("angas", "rangas");
        translationDict.put("anghang", "agas");
        translationDict.put("anghel", "anghil");
        translationDict.put("anghit", "angtit");
        translationDict.put("angil", "ngërngër");
        translationDict.put("angil", "ganggang");
        translationDict.put("angkas", "lason");
        translationDict.put("angkla", "pundo");
        translationDict.put("angkop", "bagay");
        translationDict.put("ani", "yatab");
        translationDict.put("ani", "arawas");
        translationDict.put("anihin", "yatabën");
        translationDict.put("anim", "a'nëm");
        translationDict.put("anim na beses", "mi'nëm");
        translationDict.put("anino", "alina");
        translationDict.put("anit", "katat-ulo");
        translationDict.put("anluwagi", "panday");
        translationDict.put("ano", "ani");
        translationDict.put("ano ang mga ito", "ansayti");
        translationDict.put("ano ang mga iyan", "ansain");
        translationDict.put("ano ang mga iyon", "ansaytaw");
        translationDict.put("ano ito", "ansiti");
        translationDict.put("ano iyon", "ansitaw");
        translationDict.put("ano yan", "ansiin");
        translationDict.put("ano!", "ani");
        translationDict.put("anod", "anor");
        translationDict.put("antala", "balam");
        translationDict.put("antena", "antina");
        translationDict.put("anteohos", "antipara");
        translationDict.put("antipara", "sarming");
        translationDict.put("anuman", "animan");
        translationDict.put("anyaya", "sagyat");
        translationDict.put("anyayahan", "sagyatën");
        translationDict.put("anyo", "bakas");
        translationDict.put("aparador", "aparador");
        translationDict.put("apat", "a'pat");
        translationDict.put("apat na beses", "mi'pat");
        translationDict.put("apaw", "labwa'");
        translationDict.put("apdo", "apro");
        translationDict.put("apelyido", "apilyido");
        translationDict.put("apo", "apo");
        translationDict.put("apoy", "apoy");
        translationDict.put("apula", "sëbsëb");
        translationDict.put("apulahin", "sëbsëban");
        translationDict.put("apura", "dali'");
        translationDict.put("apurahin", "apurawën");
        translationDict.put("aral", "liksyon");
        translationDict.put("aral", "adal");
        translationDict.put("aralin", "adalën");
        translationDict.put("arálin", "adalën");
        translationDict.put("araro", "adado");
        translationDict.put("araruhin", "adadwën");
        translationDict.put("araw", "awro");
        translationDict.put("ari", "ikon");
        translationDict.put("ariin", "ikunën");
        translationDict.put("arko", "arko");
        translationDict.put("armas", "armas");
        translationDict.put("aroskaldo", "aruskaldo");
        translationDict.put("asahan", "ilalwan");
        translationDict.put("asarin", "sutilën");
        translationDict.put("asawa", "asawa");
        translationDict.put("asawa", "kalamo'");
        translationDict.put("asikaso", "asikaso");
        translationDict.put("asikasuhin", "adapën");
        translationDict.put("asikasuhin", "asikaswën");
        translationDict.put("asim", "alsëm");
        translationDict.put("asiman", "alsëman");
        translationDict.put("asin", "asin");
        translationDict.put("asin dagat", "balara'");
        translationDict.put("asintahin", "asintawën");
        translationDict.put("askad", "adat");
        translationDict.put("asnan", "asinan");
        translationDict.put("aso", "aso");
        translationDict.put("asong ulol", "bagël");
        translationDict.put("aspalto", "ispalto");
        translationDict.put("aspile", "aspili");
        translationDict.put("aspilihan", "aspilyan");
        translationDict.put("asukal", "asukar");
        translationDict.put("asul", "asol");
        translationDict.put("aswang", "aswang");
        translationDict.put("at", "tan");
        translationDict.put("atado", "atado");
        translationDict.put("atay", "pait-ayi");
        translationDict.put("atay", "agtay");
        translationDict.put("ate/kuya", "angkay");
        translationDict.put("atehin/kuyahin", "angkayën");
        translationDict.put("atip", "atëp");
        translationDict.put("atis", "atis");
        translationDict.put("atras", "anunor");
        translationDict.put("atras", "atras");
        translationDict.put("atswete", "laka'");
        translationDict.put("atungal", "angak");
        translationDict.put("atupagin", "asikaswën");
        translationDict.put("awatin", "syayën");
        translationDict.put("away", "away");
        translationDict.put("awayin", "awayën");
        translationDict.put("awit", "kansyon");
        translationDict.put("awitin", "kansyunën");
        translationDict.put("ay", "ya");
        translationDict.put("ay", "kët");
        translationDict.put("Ay!", "ay");
        translationDict.put("ayaw", "andi'");
        translationDict.put("ayon", "bulon");
        translationDict.put("ayon", "ayon");
        translationDict.put("ayos", "alinya");
        translationDict.put("ayos", "unong");
        translationDict.put("ayos", "rimpës");
        translationDict.put("ayun", "suoy");
        translationDict.put("ayusin", "unungën");
        translationDict.put("ayusin", "rimpësën");

    }

    public String translate(String word) {
        return translationDict.getOrDefault(word, "Translation not available");
    }
}
